Error in generation thread: shape mismatch: value tensor of shape [1180, 1536] cannot be broadcast to indexing result of shape [1805, 1536]
Traceback (most recent call last):
  File "/home/aiuser/VibeVoice-Community/demo/gradio_demo.py", line 537, in _generate_with_streamer
    outputs = self.model.generate(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/aiuser/VibeVoice-Community/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiuser/VibeVoice-Community/vibevoice/modular/modeling_vibevoice_inference.py", line 500, in generate
    outputs = self(
              ^^^^^
  File "/home/aiuser/VibeVoice-Community/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiuser/VibeVoice-Community/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiuser/VibeVoice-Community/vibevoice/modular/modeling_vibevoice_inference.py", line 246, in forward
    inputs_embeds[speech_input_mask] = speech_embeds
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
RuntimeError: shape mismatch: value tensor of shape [1180, 1536] cannot be broadcast to indexing result of shape [1805, 1536]